// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7Hd59s1CxUyy_mdBCKQ3cYBf_zTAu2JY',
    appId: '1:473014855439:web:df2f40b1e4874acb15807a',
    messagingSenderId: '473014855439',
    projectId: 'myporfolio-5edb7',
    authDomain: 'myporfolio-5edb7.firebaseapp.com',
    storageBucket: 'myporfolio-5edb7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsQ2Z0Z-OCaoFIxTPMMb2syAGxohSZ9GQ',
    appId: '1:473014855439:android:53ad49b1d1bfa49115807a',
    messagingSenderId: '473014855439',
    projectId: 'myporfolio-5edb7',
    storageBucket: 'myporfolio-5edb7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvarWb9RjZ1WNlUWb9GWyN1YwvDmMA37k',
    appId: '1:473014855439:ios:83a2f885d1f4b3be15807a',
    messagingSenderId: '473014855439',
    projectId: 'myporfolio-5edb7',
    storageBucket: 'myporfolio-5edb7.appspot.com',
    iosBundleId: 'com.example.flutterPortfolio',
  );
}
